name: post
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-160.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #routes
  go_router: ^9.0.3

  #state_managment
  flutter_bloc: ^8.1.3

  #size_correction
  flutter_screenutil: ^5.8.4

  #image
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3

  #freezed
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #network
  dio: ^5.2.1+1
  logger: ^1.4.0
  dartz: ^0.10.1

  #toast
  flutter_styled_toast: ^2.1.3

  #permission
  permission_handler: ^10.4.3
  device_info_plus:


dev_dependencies:
  flutter_test:
    sdk: flutter

  #freezed
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProText.ttf
